services:
  app:
    image: kangminhyeok/travel-hub-api:latest
    container_name: travel-hub-api
    ports:
      - "8009:8009"
    volumes:
      - ./.oci/:/app/.oci/
    environment:
      - SPRING_PROFILES_ACTIVE=docker