services:
  app:
    image: kangminhyeok/travel-hub-api:latest
    container_name: travel-hub-api
    ports:
      - "8009:8009"
    volumes:
      - ./logback-spring.xml:/app/logback-spring.xml
      - ./log:/app/log
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_CONFIG=/app/logback-spring.xml