app:
  cron:
    reload: 0 * * * * *
    refresh-place: 0 0 0 * * *
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # thymeleaf 설정
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    travel-hub:
      jdbc-url: jdbc:mysql://localhost:3306/travel_hub?autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
      username: test
      password: test
      connection-timeout: 60000
      idle-timeout: 30000
      max-lifetime: 420000
      validation-timeout: 10000
      maximum-pool-size: 1
      minimum-idle: 1
      pool-name: connectionPool_dev
  data:
    redis:
      host: localhost
      port: 6379

elastic:
  place-index: dev_travel

server:
  port: 80
# logging:
#  config: ./logback-spring.xml