app:
  cron:
    reload: 0 * * * * *
    refresh-place: 0 0 0 * * *
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true  # thymeleaf 설정
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  datasource:
    url: jdbc:mysql://140.83.87.41:9500/travel_hub?autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: superHMN
    password: travelHubPwd140$!
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    travel-hub:
#      jdbc-url: jdbc:mysql://localhost:3306/travel_hub?autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
#      username: root
#      password: Kenta00@
#      connection-timeout: 60000
#      idle-timeout: 30000
#      max-lifetime: 420000
#      validation-timeout: 10000
#      maximum-pool-size: 1
#      minimum-idle: 1
#      pool-name: connectionPool_dev
  data:
    redis:
      host: 141.147.149.58
      port: 9700
      password: travelHubPwd

elastic:
  place-index: dev_travel

server:
  port: 80
# logging:
#  config: ./logback-spring.xml